Fix ModelCard.config AttributeError in tinygrad model loader
The ModelCard object doesn't have a 'config' attribute. Changed to use
default config based on model size instead. This fixes the model loading
failure where it was trying to access shard_metadata.model_card.config.

Fixes: AttributeError: 'ModelCard' object has no attribute 'config'